/**
 * Mirrors plan_index.json generated by the data pipeline.
 *
 * Source of truth: pipeline/src/pipeline/plans/plan_index.py
 * These types have to updated if the _OUTPUT_SCHEMA_VERSION in
 * plan_index.py changes.
 */

// --- Sentinel / Utility Types ---

/** Field is not curated yet. */
export const PENDING = 'pending';
export type PendingSentinel = typeof PENDING;

/** Field is curated and found to be indeterminable. */
export const UNKNOWN = 'unknown';
export type UnknownSentinel = typeof UNKNOWN;

export type Sentinel = PendingSentinel | UnknownSentinel;

export type IsoDate = string;

/**
 * Free-prose field.
 */
export type ProseField = string;

/**
 * Reference to another plan_id, the pending sentinel, or null.
 */
export type PlanRefField = string | null;

// --- Curation Sentitive Value Types ---

export type OriginLiteral = 'legislature' | 'court' | 'commission' | 'remedial' | 'unchanged';

export type OriginField = OriginLiteral | Sentinel;

export type DateField = IsoDate | Sentinel | null;

export type StruckDownField = boolean | Sentinel;

export type CurationStatus = 'pending' | 'partial' | 'curated';

// --- Sub-records ---

export type CourtCitationRole = 'enabling' | 'invalidating' | 'remedial' | 'affirming' | 'context';

export interface CourtCitation {
	case: string;
	citation: string;
	role: CourtCitationRole;
	url: string;
	archived_url: string | null;
}

export interface Source {
	url: string;
	accessed: IsoDate;
	archived: string | null;
}

// --- Plan Record ----

export type Chamber = 'congressional';

export interface Plan {
	// Identity and provenance
	plan_id: string;
	state: string;
	chamber: Chamber;
	congress_start: number;
	congress_end: number | null;
	schema_version: 1;

	// Dates
	enacted_date: DateField;
	effective_date: DateField;

	// Curation-sensitive
	origin: OriginField;
	origin_details: ProseField;

	struck_down: StruckDownField;
	struck_down_details: ProseField;
	struck_down_districts: number[];

	superseded_by: PlanRefField;
	predecessor: PlanRefField;

	court_citations: CourtCitation[];
	sources: Source[];
	notes: ProseField;

	// Status tracking
	curation_status: CurationStatus;
	curation_last_reviewed: IsoDate | null;

	// Open extensions (pipeline passes through untouched)
	extensions: Record<string, unknown>;

	// Intentially excludes source_file and source_commit (build internals)
}

// --- Top-level Shape ---

export type PlansByState = Record<string, Record<string, Plan>>;

export interface PlanIndex {
	schema_version: 1;
	plans: PlansByState;
}
